#!/bin/bash
# Hook para validar formato de mensaje de commit

pattern="^(feat|fix|chore|reformat|style|refactor|perf|test|docs|ci|build|revert): [A-Za-z].*"
commit_msg=$(cat "$1")

if [[ ! $commit_msg =~ $pattern ]]; then
    echo "Error: Invalid commit message fotrmat, use 'type: Aaaaa bbbbb ccccc'"
    exit 1
fi

exit 0
