#!/bin/bash
# Hook para validar formato de mensaje de commit

pattern="^(feat|fix|chore|reformat|style|refactor|perf|test|docs|ci|build|revert): [A-Za-z].*"
commit_msg=$(cat "$1")

if [[ ! $commit_msg =~ $pattern ]]; then
    echo "Error: El mensaje del commit debe tener el formato 'type: Aaaaaaaa bbbbbbbb cccccc'"
    exit 1
fi

exit 0
